#!/usr/bin/env python3
"""Wildfire smoke map video — dark 3-D terrain, real smoke, live fire dots.

Produces a square animation in the style Miloš Popović popularised: forge3d
renders the terrain in dark relief, CAMS aerosol optical depth drifts over it as
real smoke, NASA FIRMS VIIRS detections appear as fire dots that glow for 12
hours, and counters tick up. 1080x1080, 24 fps, MP4 plus GIF.

Adapted from a standalone pipeline that ran on one machine, in one directory,
for one region. Three things had to change for it to be installable:

  * the region is now a parameter, not an edit to config.py. The scenario writes
    a generated config into the run directory and stages the proven scripts
    beside it, so the pipeline itself is untouched and still reproducible.
  * the FIRMS feed follows the AOI. FIRMS publishes 7-day CSVs per continent and
    the original hardcoded SouthEast_Asia, so anywhere else returned no fires at
    all -- silently, because an empty bbox filter looks like a quiet week.
  * the heavy prerequisites are checked up front with instructions, rather than
    failing several minutes in with a traceback.

NOT an Earth Engine scenario: every input here is a public HTTP endpoint
(Open-Meteo air quality for CAMS, FIRMS CSVs, AWS terrarium DEM tiles), so it
runs with no Earth Engine account at all.

Needs: pip install 'earthchange[video]', plus ffmpeg and a working Vulkan
device (a GPU, or mesa-vulkan-drivers for headless llvmpipe).
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

PIPELINE = Path(__file__).resolve().parent / "pipeline"

# FIRMS publishes one 7-day CSV per continent; the bbox has to be inside the
# region you ask for or you get an empty file rather than an error.
FIRMS_REGIONS = [
    "SouthEast_Asia", "South_Asia", "Russia_Asia", "Australia_NewZealand",
    "Europe", "Africa", "North_America", "South_America", "Central_America",
    "Canada", "USA_contiguous_and_Hawaii",
]
# Rough continental extents, only good enough to pick a feed and to warn when
# the guess looks wrong. Not a substitute for the user naming one.
_REGION_BOX = {
    "SouthEast_Asia": (90, -12, 145, 30),
    "South_Asia": (60, 0, 92, 40),
    "Australia_NewZealand": (110, -50, 180, -10),
    "Europe": (-25, 34, 45, 72),
    "Africa": (-20, -36, 55, 38),
    "South_America": (-82, -57, -34, 13),
    "Central_America": (-118, 7, -58, 33),
    "North_America": (-170, 14, -50, 80),
    "Russia_Asia": (45, 40, 180, 78),
}


def guess_firms_region(lon, lat):
    """Pick a FIRMS continental feed from the AOI centre."""
    for name, (w, s, e, n) in _REGION_BOX.items():
        if w <= lon <= e and s <= lat <= n:
            return name
    return None


def preflight(basemap=True):
    """Check the heavy prerequisites before anything downloads.

    This pipeline takes several minutes and pulls hundreds of megabytes. Failing
    at the encode step because ffmpeg is missing wastes all of it.
    """
    missing = []
    if shutil.which("ffmpeg") is None:
        missing.append(
            "ffmpeg is not on PATH — needed to encode the MP4 and GIF.\n"
            "      macOS: brew install ffmpeg\n"
            "      Debian/Ubuntu: sudo apt install ffmpeg")
    for mod, hint in (("numpy", None), ("scipy", None), ("pandas", None),
                      ("PIL", "pillow"), ("requests", None)):
        try:
            __import__(mod)
        except ImportError:
            missing.append(f"{hint or mod} is not installed")
    if basemap:
        try:
            import forge3d                                        # noqa: F401
        except ImportError:
            missing.append(
                "forge3d is not installed — needed for the 3-D terrain render.\n"
                "      pip install 'earthchange[video]'\n"
                "      Headless machines also need a Vulkan driver: "
                "sudo apt install mesa-vulkan-drivers")
    if missing:
        raise SystemExit(
            "smoke-video needs a few things first:\n  · "
            + "\n  · ".join(missing)
            + "\n\n  Everything else installs with: pip install 'earthchange[video]'")


def _write_config(work, bbox, cities, title, subtitle, region, size, labels=None):
    """Generate config.py for this run, instead of editing the shipped one."""
    w, s, e, n = bbox
    lines = [
        '"""Generated by earthchange -s smoke-video. Edit and re-run the',
        'individual steps if you want to tweak this particular animation."""',
        "from pathlib import Path",
        "",
        "WORK = Path(__file__).resolve().parent",
        "DATA = WORK / 'data'",
        "FRAMES = WORK / 'frames'",
        "OUT = WORK / 'out'",
        "for d in (DATA, FRAMES, OUT):",
        "    d.mkdir(parents=True, exist_ok=True)",
        "",
        f"LON_MIN, LON_MAX = {w}, {e}",
        f"LAT_MIN, LAT_MAX = {s}, {n}",
        f"WIDTH = HEIGHT = {size}",
        f"FIRMS_REGION = {region!r}",
        "",
        f"TITLE = {title!r}",
        f"SUBTITLE = {subtitle!r}",
        "",
        "# Graticule spacing, scale bar, DEM zoom and terrain smoothing are all",
        "# derived from the bbox. Override DEM_ZOOM or TERRAIN_SMOOTH here if a",
        "# particular landscape wants something else.",
        "CITIES = [",
    ]
    for nm, clon, clat, major in cities:
        lines.append(f"    ({nm!r}, {clon}, {clat}, {bool(major)}),")
    lines.append("]")
    lines.append("")
    lines.append("REGION_LABELS = [   # (text, lon, lat, big)")
    for txt, rlon, rlat, big in (labels or []):
        lines.append(f"    ({txt!r}, {rlon}, {rlat}, {bool(big)}),")
    lines.append("]")
    (work / "config.py").write_text("\n".join(lines) + "\n")


def _stage(work):
    """Copy the pipeline beside the generated config.

    Staged rather than run in place: the scripts import `config` from their own
    directory, and a shared install directory would mean two concurrent runs
    fighting over one region.
    """
    work.mkdir(parents=True, exist_ok=True)
    for f in PIPELINE.iterdir():
        if f.suffix in (".py", ".sh") and f.name != "config.py":
            shutil.copy2(f, work / f.name)
    fonts = PIPELINE / "fonts"
    if fonts.is_dir():
        shutil.copytree(fonts, work / "fonts", dirs_exist_ok=True)
    return work


def _run(work, script, *args, label="", env=None):
    """One pipeline step, with this interpreter rather than a bare python3."""
    cmd = ([sys.executable, str(work / script), *args] if script.endswith(".py")
           else ["bash", str(work / script), *args])
    print(f"  {label or script} ...", flush=True)
    r = subprocess.run(cmd, cwd=str(work),
                       env={**os.environ, **(env or {})} if env else None)
    if r.returncode != 0:
        raise SystemExit(f"  smoke-video failed at {script} "
                         f"(exit {r.returncode}). The staged pipeline is in "
                         f"{work} — you can re-run that step directly.")


def _cities_from(spec, bbox):
    """Place labels from `--video-cities "Name,lon,lat[,major]; ..."`.

    There is no auto-discovery here on purpose. Open-Meteo's geocoding endpoint
    searches by NAME and cannot list what falls inside a bounding box, so an
    automatic version would have to guess names to look up and would quietly
    return nothing most of the time. Better to leave the frame unlabelled and
    say how to add labels than to ship a feature that silently does not work.
    """
    if not spec:
        return []
    w, s, e, n = bbox
    out = []
    for part in spec.split(";"):
        part = part.strip()
        if not part:
            continue
        bits = [b.strip() for b in part.split(",")]
        if len(bits) < 3:
            raise SystemExit(
                f"--video-cities entry {part!r} needs Name,lon,lat[,major] — "
                f"e.g. 'Ketapang,109.977,-1.839,major; Sandai,110.517,-1.250'")
        try:
            clon, clat = float(bits[1]), float(bits[2])
        except ValueError:
            raise SystemExit(f"--video-cities: bad coordinates in {part!r}")
        if not (w <= clon <= e and s <= clat <= n):
            print(f"  note: {bits[0]} ({clat:.3f}, {clon:.3f}) is outside the "
                  f"frame and will not be drawn")
        out.append((bits[0], clon, clat,
                    len(bits) > 3 and bits[3].lower() in ("major", "true", "1")))
    return out


def run(backend, lat, lon, radius, name, run_dir, run_id, config_key=None,
        bbox=None, admin=None, size=1080, firms_region=None, title=None,
        subtitle=None, cities=None, labels=None, keep=True):
    """Render the wildfire smoke map video for an area."""
    preflight()

    if bbox:
        w, s, e, n = bbox
    else:
        # Square-ish degree box from the radius, since the frame is square.
        import math
        d = max(radius, 20) / 111.0
        dlon = d / max(math.cos(math.radians(lat)), 0.2)
        w, s, e, n = lon - dlon, lat - d, lon + dlon, lat + d
    clon, clat = (w + e) / 2, (s + n) / 2

    region = firms_region or guess_firms_region(clon, clat)
    if not region:
        raise SystemExit(
            f"Could not work out which FIRMS feed covers {clat:.2f}, "
            f"{clon:.2f}. Name one with --firms-region: "
            f"{', '.join(FIRMS_REGIONS)}")

    work = _stage(Path(run_dir) / "pipeline")
    places = _cities_from(cities, (w, s, e, n))
    marks = _cities_from(labels, (w, s, e, n)) if labels else []
    _write_config(work, (w, s, e, n), places,
                  title or "WILDFIRE SMOKE",
                  subtitle or f"{name.upper()} · {{period}} · CAMS + VIIRS",
                  region, size, marks)

    print(f"  {name}: bbox {w:.2f},{s:.2f} → {e:.2f},{n:.2f} · "
          f"FIRMS {region} · {size}x{size}")
    if places:
        print(f"  {len(places)} place labels")
    else:
        print("  no place labels — add them with --video-cities "
              "'Name,lon,lat,major; …', or edit CITIES in\n"
              f"    {work / 'config.py'} and re-run compose.py")

    _run(work, "download_dem.py", label="1/5 terrain tiles")
    _run(work, "download_fires.py", label="1/5 FIRMS fires")
    _run(work, "download_aod.py", label="1/5 CAMS smoke")
    _run(work, "render_basemap.py", label="2/5 forge3d terrain")
    _run(work, "regrade.py", label="3/5 dark grade")
    _run(work, "compose.py", "all", label="4/5 frames")
    slug = "".join(c if c.isalnum() or c in "-_" else "_" for c in name).lower()
    _run(work, "encode.sh", label="5/5 encode",
         env={"OUT_NAME": f"{slug}_wildfire_smoke"})

    out = work / "out"
    made = sorted(str(p) for p in out.glob("*") if p.suffix in (".mp4", ".gif"))
    for p in made:
        # Lift the finished video out of the staging directory.
        shutil.copy2(p, Path(run_dir) / Path(p).name)
        print(f"Saved: {os.path.normpath(Path(run_dir) / Path(p).name)}")
    if not keep:
        shutil.rmtree(work, ignore_errors=True)

    stats = {"run_id": run_id, "scenario": "smoke-video", "name": name,
             "bbox": [w, s, e, n], "firms_region": region, "size": size,
             "cities": [c[0] for c in places],
             "sources": {
                 "smoke": "CAMS aerosol optical depth via Open-Meteo Air Quality",
                 "fires": f"NASA FIRMS VIIRS 7-day, {region} feed "
                          "(SNPP + NOAA-20 + NOAA-21)",
                 "terrain": "AWS terrarium elevation tiles",
             },
             "outputs": {"video": [Path(p).name for p in made]},
             "note": ("A 7-day rolling window: FIRMS public feeds only carry "
                      "the last week, so this shows the current episode and "
                      "cannot be run for a past one. Fire dots are detections, "
                      "not burned area.")}
    import json
    with open(Path(run_dir) / "stats.json", "w") as f:
        json.dump(stats, f, indent=2)
    return stats
