"""Turn a fetched stack folder into a MintPy time series.

Encodes the settings this stack actually needs. Each one below cost real
debugging on the same data, and every one of them failed SILENTLY -- the run
continued and produced a shorter or emptier result rather than stopping:

  * Grid normalisation. HyP3 sizes each geocoded product to its own granule
    footprint, so the raster size drifts a pixel or two between acquisitions,
    and load_data keeps ONLY products matching the modal size. That silently
    discarded 198 of 354 descending and 189 of 351 ascending interferograms,
    and truncated the ascending record eleven months short.

  * unwrapError.method = no, plus obsDatasetName pinned. Both correction
    methods need connectComponent, which HyP3 GAMMA does not produce.
    phase_closure writes an all-zero dataset that obsDatasetName=auto then
    PREFERS over the good raw phase; the inversion reports 0 pixels of 1.6
    million with no error.

  * minTempCoh = 0.1. MintPy builds the reliable-pixel mask BEFORE
    correct_troposphere. Uncorrected, median temporal coherence here is ~0.06,
    so the 0.7 default passes one pixel and aborts the run ahead of the very
    correction that would fix it. Permissive by design: it lets the run finish,
    it does not certify the pixels.

  * deramp = no. A plane fit needs pixels spread across the frame; with a
    sparse, clustered mask the fit is singular and the field explodes to 1e22.

  * lv_theta / lv_phi for geometry. MintPy converts HyP3 angles itself, but
    only for files with those names -- prep_hyp3 tags them UNIT=radian and
    stackDict applies 90-deg(theta) and deg(phi)-90. It does none of that for
    inc_map, which then needs converting by hand.

    python3 opensciencelab_run.py stack/insar_asc
    python3 opensciencelab_run.py stack/insar_asc --run
"""

import argparse
import glob
import os
import subprocess
import sys

CONFIG = """\
# Generated by opensciencelab_run.py
mintpy.load.processor        = hyp3
mintpy.load.unwFile          = ../hyp3/*/*_unw_phase.tif
mintpy.load.corFile          = ../hyp3/*/*_corr.tif
mintpy.load.demFile          = ../hyp3/*/*_dem.tif
{geometry}
# Both unwrap-error methods need connectComponent, absent from HyP3 GAMMA.
# phase_closure fails silently by writing zeros, which auto then prefers.
mintpy.unwrapError.method              = no
mintpy.networkInversion.obsDatasetName = unwrapPhase

# This mask is built BEFORE the tropospheric correction. 0.7 is unreachable
# here and aborts the run before ERA5 ever executes.
mintpy.networkInversion.minTempCoh     = 0.1

# A plane fit over a sparse, clustered mask is singular; it produced 1e22 mm.
mintpy.deramp                          = no

mintpy.troposphericDelay.method        = pyaps
mintpy.topographicResidual             = yes
mintpy.solidEarthTides                 = yes
mintpy.reference.minCoherence          = 0.3
mintpy.network.tempBaseMax             = 60
"""


def run(cmd, cwd=None):
    try:
        p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    except FileNotFoundError:
        # In OpenScienceLab this means the notebook kernel is not the MintPy
        # environment. Say so, rather than raising a subprocess traceback that
        # buries the one useful fact.
        raise SystemExit(
            f"{cmd[0]} is not on PATH.\n"
            f"In OpenScienceLab, switch the kernel to the MintPy environment "
            f"(or 'conda activate mintpy') and rerun.")
    if p.returncode != 0:
        tail = (p.stderr or p.stdout).splitlines()[-3:]
        print(f"    FAILED rc={p.returncode}: {tail}")
    return p.returncode


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("stack", help="e.g. stack/insar_asc")
    ap.add_argument("--run", action="store_true",
                    help="also launch smallbaselineApp (long)")
    ap.add_argument("--skip-normalize", action="store_true")
    a = ap.parse_args()

    hyp3_dir = os.path.join(a.stack, "hyp3")
    if not os.path.isdir(hyp3_dir):
        raise SystemExit(f"{hyp3_dir} not found — run opensciencelab_fetch.py first")

    products = sorted(d for d in glob.glob(f"{hyp3_dir}/*") if os.path.isdir(d))
    print(f"{len(products)} products in {hyp3_dir}")

    # 1. One grid, or load_data silently drops the odd sizes.
    if not a.skip_normalize:
        here = os.path.dirname(os.path.abspath(__file__))
        norm = os.path.join(here, "normalize_grid.py")
        if os.path.exists(norm):
            print("\n=== normalising grids ===")
            run([sys.executable, norm, a.stack])
        else:
            print("normalize_grid.py not alongside this script — SKIPPED. "
                  "Expect load_data to drop products whose size differs.")

    # 2. prep_hyp3 per product: 705 products is far past ARG_MAX, and a loop
    #    survives one bad product instead of losing the batch. Rasters only --
    #    handing prep_hyp3 the .txt makes it try to open it with GDAL and abort.
    print("\n=== prep_hyp3 ===")
    ok = bad = 0
    for i, d in enumerate(products, 1):
        rasters = [p for p in sorted(glob.glob(f"{d}/*.tif"))]
        if not rasters:
            continue
        if run(["prep_hyp3.py"] + rasters) == 0:
            ok += 1
        else:
            bad += 1
        if i % 50 == 0 or i == len(products):
            print(f"  {i}/{len(products)}  ok {ok}, failed {bad}", flush=True)

    # 3. Config, naming geometry only if it is actually there.
    mintpy_dir = os.path.join(a.stack, "mintpy")
    os.makedirs(mintpy_dir, exist_ok=True)
    geom = []
    if glob.glob(f"{hyp3_dir}/*/*_lv_theta.tif"):
        geom.append("mintpy.load.incAngleFile     = ../hyp3/*/*_lv_theta.tif")
    if glob.glob(f"{hyp3_dir}/*/*_lv_phi.tif"):
        geom.append("mintpy.load.azAngleFile      = ../hyp3/*/*_lv_phi.tif")
    if not geom:
        geom.append("# No lv_theta/lv_phi found: no azimuth angle, so an "
                    "asc/desc decomposition\n# cannot read look directions "
                    "and would have to assume them.")

    cfg = os.path.join(mintpy_dir, "earthchange.cfg")
    with open(cfg, "w") as f:
        f.write(CONFIG.format(geometry="\n".join(geom)))
    print(f"\nwrote {cfg}")
    for line in geom:
        print(f"  {line}")

    print(f"\nprep_hyp3: {ok} ok, {bad} failed")
    if not a.run:
        print(f"\nNext:\n  cd {mintpy_dir} && smallbaselineApp.py earthchange.cfg"
              f"\n  python3 check_stack.py {a.stack}   # verify nothing was dropped")
        return 0

    # Stop BEFORE residual_RMS. That step dies in matplotlib
    # ("Axis limits cannot be NaN or Inf") on both tracks of this stack -- a
    # plotting failure, with every science product already written. Running the
    # whole app instead means hours of correct work discarded by a broken
    # figure, so end at correct_topography and compute velocity directly.
    print("\n=== smallbaselineApp (load_data .. correct_topography) ===")
    rc = run(["smallbaselineApp.py", "earthchange.cfg",
              "--end", "correct_topography"], cwd=mintpy_dir)
    if rc != 0:
        print("  stopped early — inspect the log before continuing")
        return rc

    # Most-corrected file present wins; both tracks must end on the SAME one or
    # a later asc/desc comparison measures processing asymmetry, not ground.
    for cand in ("timeseries_SET_ERA5_demErr.h5",
                 "timeseries_ERA5_demErr.h5",
                 "timeseries_SET_ERA5.h5",
                 "timeseries_ERA5.h5"):
        if os.path.exists(os.path.join(mintpy_dir, cand)):
            print(f"\n=== velocity from {cand} ===")
            rc = run(["timeseries2velocity.py", cand,
                      "-o", "velocityERA5.h5"], cwd=mintpy_dir)
            if rc == 0:
                print(f"  wrote {mintpy_dir}/velocityERA5.h5")
            return rc

    print("\nno corrected time series found — check the log")
    return 1


if __name__ == "__main__":
    sys.exit(main())
